### ISSUE TITLE
Add smooth config/auth command

### ISSUE THREAD

**Issue by vaugenwake** [matthewrobinsondev/lazyjira#4]
Add a command like `lazy-jira auth init` to setup your auth and configuration and store it on device in the `.config` directory and load in vars when app is initalized

@matthewrobinsondev What do you think?

**Comment by matthewrobinsondev** [comment]
Great idea, think it could probably just be `lazyjira auth` or `lazyjira init` for peak laziness unless theres any other sub commands you have in mind
